on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          passphrase: ${{ secrets.PASSPHRASE }} 
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh 
            cd ${{ secrets.WORK_DIR }} 
            git fetch  
            git pull 
            yarn  
            yarn build  
            pm2 start yarn --name clf_app -- --port 3001
            pm2 restart clf_app

      # - name: Install PM2
      #   run: npm install pm2@latest -g

      # - name: Restart PM2 Process
      #   run: pm2 restart dhkim
